export const experiences = [
  { id:1, title:"Software Engineer Intern", company:"Hotspring", startDate:"2024-08", endDate:"2024-12", description:"Developed full-stack Django and React features, automated S3 workflows, improved UI responsiveness, optimized backend queries, and enhanced live production performance.", technologies:["React","Node.js","AWS","Docker"], priority: 5 },
  { id:2, title:"Software Engineer Intern", company:"TopSource Worldwide", startDate:"2024-06", endDate:"2024-08", description:"Developed scalable SaaS modules with React, Django, and PostgreSQL, optimized APIs and UI, improved reliability, and streamlined Agile-based development.", technologies:["Vue.js","Python","PostgreSQL"], priority: 5 },
  { id:3, title:"Research Assistant - Hand Pose Estimation and Self-Supervised Learning for ASL Recognition", company:"The University of Texas at Arlington", startDate:"2024-08", endDate:"2025-08", description:"Researched ASL hand pose estimation using AI, implementing DTW and CNN-GCN models to enhance gesture recognition, robustness, and accessibility.", technologies:["JavaScript","HTML/CSS","Git"], priority: 3 },
  { id:4, title:"Research Assistant - Human Pose Estimation and AI Systems", company:"The University of Texas at Arlington", startDate:"2024-10", endDate:null, description:"Researched deep learning-based human pose estimation using CNNs, GCNs, and Transformers; published in IEEE Access; improved model accuracy and accessibility.", technologies:["Python","JavaScript","REST APIs"], priority: 3 },
  { id:5, title:"Supplemental Instruction Leader", company:"Academic Success Center (UTA)", startDate:"2025-01", endDate:null, description:"Led peer instruction for Data Structures, Algorithms, and Discrete Math; created interactive activities, tutoring sessions, and review materials to boost comprehension.", technologies:["HTML","CSS","jQuery","WordPress"], priority: 2 },
  { id:6, title:"Undergraduate Research Assistant", company:"Primal Lab (UTA)", startDate:"2025-05", endDate:null, description:"Researched event-based computer vision using CNNs and ResNet models, improving event data representations and enabling real-time structural failure prediction systems.", technologies:["Event Vision", "PyTorch"], priority: 4},
  { id:7, title:"APSI Student Assistant", company:"Honor's College (UTA)", startDate:"2025-06", endDate:"2025-06", description:"Organized and managed a large-scale APSI campus event with 500+ attendees, coordinating logistics, teams, and operations to ensure seamless execution.", technologies: ["Communication"], priority: 1},
  { id:8, title:"ACM Create Member", company:"ACM (UTA)", startDate:"2025-09", endDate:null, description:"Serving as ACM Create Member, developing MavsPrep, a web platform that provides UTA students with organized study materials and academic resources.", technologies: ["NextJS"], priority: 3}
];

export const projects = [
  { id:1, title:"E-Commerce Platform", description:"A full-stack e-commerce solution with payment integration, inventory management, and admin dashboard.", icon:"🚀", tags:["React","Node.js","MongoDB","Stripe"], stars:245, github:"https://github.com/aroudrasthakur/ecommerce-platform", demo:"https://demo-ecommerce.com", priority: 0 },
  { id:2, title:"AI Image Recognition", description:"Computer vision application using TensorFlow for real-time object detection and classification.", icon:"🤖", tags:["Python","TensorFlow","OpenCV","Flask"], stars:189, github:"https://github.com/aroudrasthakur/ai-image-recognition", demo:null, priority: 0 },
  { id:3, title:"Task Management App", description:"Collaborative task manager with real-time updates, team features, and analytics dashboard.", icon:"📱", tags:["Vue.js","Firebase","Tailwind"], stars:167, github:"https://github.com/aroudrasthakur/task-manager", demo:"https://demo-taskmanager.com", priority: 0 },
  { id:4, title:"Weather Dashboard", description:"Real-time weather tracking application with beautiful visualizations and location-based forecasts.", icon:"🌤️", tags:["React","Chart.js","API Integration"], stars:134, github:"https://github.com/aroudrasthakur/weather-dashboard", demo:"https://demo-weather.com", priority: 0 },
  { id:5, title:"Social Media Analytics", description:"Comprehensive analytics tool for tracking social media metrics across multiple platforms.", icon:"📊", tags:["Node.js","Express","D3.js","PostgreSQL"], stars:98, github:"https://github.com/aroudrasthakur/social-analytics", demo:null, priority: 0 },
  { id:6, title:"Portfolio Generator", description:"Automated portfolio website generator with customizable themes and deployment options.", icon:"🎨", tags:["JavaScript","HTML/CSS","GitHub Actions"], stars:87, github:"https://github.com/aroudrasthakur/portfolio-generator", demo:"https://demo-portfolio-gen.com", priority: 0 },
  { id:7, title:"Fitness Tracker", description:"Mobile-first fitness tracking app with workout plans, progress charts, and social features.", icon:"💪", tags:["React Native","Firebase","Redux"], stars:76, github:"https://github.com/aroudrasthakur/fitness-tracker", demo:null, priority: 0 }
];

export function formatDate(dateStr){
  if(!dateStr) return 'Present';
  const [y,m]=dateStr.split('-');
  const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${months[parseInt(m)-1]} ${y}`;
}