export const experiences = [
  { id:1, title:"Software Engineer Intern", company:"Hotspring", startDate:"2024-08", endDate:"2024-12", description:"Developed full-stack Django and React features, automated S3 workflows, improved UI responsiveness, optimized backend queries, and enhanced live production performance.", technologies:["React","Node.js","AWS","Docker"], priority: 5 },
  { id:2, title:"Software Engineer Intern", company:"TopSource Worldwide", startDate:"2024-06", endDate:"2024-08", description:"Developed scalable SaaS modules with React, Django, and PostgreSQL, optimized APIs and UI, improved reliability, and streamlined Agile-based development.", technologies:["Vue.js","Python","PostgreSQL"], priority: 5 },
  { id:3, title:"Research Assistant - Hand Pose Estimation and Self-Supervised Learning for ASL Recognition", company:"The University of Texas at Arlington", startDate:"2024-08", endDate:"2025-08", description:"Researched ASL hand pose estimation using AI, implementing DTW and CNN-GCN models to enhance gesture recognition, robustness, and accessibility.", technologies:["JavaScript","HTML/CSS","Git"], priority: 3 },
  { id:4, title:"Research Assistant - Human Pose Estimation and AI Systems", company:"The University of Texas at Arlington", startDate:"2024-10", endDate:null, description:"Researched deep learning-based human pose estimation using CNNs, GCNs, and Transformers; published in IEEE Access; improved model accuracy and accessibility.", technologies:["Python","JavaScript","REST APIs"], priority: 3 },
  { id:5, title:"Supplemental Instruction Leader", company:"Academic Success Center (UTA)", startDate:"2025-01", endDate:null, description:"Led peer instruction for Data Structures, Algorithms, and Discrete Math; created interactive activities, tutoring sessions, and review materials to boost comprehension.", technologies:["HTML","CSS","jQuery","WordPress"], priority: 2 },
  { id:6, title:"Undergraduate Research Assistant", company:"Primal Lab (UTA)", startDate:"2025-05", endDate:null, description:"Researched event-based computer vision using CNNs and ResNet models, improving event data representations and enabling real-time structural failure prediction systems.", technologies:["Event Vision", "PyTorch"], priority: 4},
  { id:7, title:"APSI Student Assistant", company:"Honor's College (UTA)", startDate:"2025-06", endDate:"2025-06", description:"Organized and managed a large-scale APSI campus event with 500+ attendees, coordinating logistics, teams, and operations to ensure seamless execution.", technologies: ["Communication"], priority: 1},
  { id:8, title:"ACM Create Member", company:"ACM (UTA)", startDate:"2025-09", endDate:null, description:"Serving as ACM Create Member, developing MavsPrep, a web platform that provides UTA students with organized study materials and academic resources.", technologies: ["NextJS"], priority: 3}
];

export const projects = [
  { id:1, title:"LangPal", description:"Language learning partner app connecting users with language exchange partners worldwide. Features real-time chat, partner discovery, safety features, and dark mode support.", icon:"🌍", tags:["React Native","TypeScript","Expo","AsyncStorage"], stars:0, github:"https://github.com/aroudrasthakur/LangPal-Prototype", demo:null, priority: 10 },
  { id:2, title:"TicketFinder", description:"Ticketing engine that helps users find concerts and games using GoogleAPI, TicketMaster API, and IpInfo API with an intuitive interface.", icon:"🎫", tags:["TypeScript","Python","React","Django"], stars:0, github:"https://github.com/aroudrasthakur/TicketFinder", demo:null, priority: 9 },
  { id:3, title:"Store Management System", description:"PHP + MySQL based web application for managing stores, vendors, and inventory. Features CRUD operations, stock tracking, and vendor management.", icon:"🏪", tags:["PHP","MySQL","Apache","CSS"], stars:0, github:"https://github.com/aroudrasthakur/StoreManagementAndWebInterface", demo:null, priority: 8 },
  { id:4, title:"ASL Similarity Measures", description:"Research project implementing Dynamic Time Warping (DTW) and similarity measures for American Sign Language recognition and gesture analysis.", icon:"🤖", tags:["Python","DTW","Machine Learning","Computer Vision"], stars:0, github:"https://github.com/aroudrasthakur/Similarity-Measures", demo:null, priority: 7 },
  { id:5, title:"Embedded Systems Projects", description:"Collection of C-based projects including HealthMart Pharmacy system, Virtual Chatbot, Alarm System, Sonar Range Finder, and Temperature Sensor on Raspberry Pi 4.", icon:"�", tags:["C","Raspberry Pi","Embedded Systems","IoT"], stars:0, github:"https://github.com/aroudrasthakur/Projects", demo:null, priority: 6 },
  { id:6, title:"Personal Portfolio Website", description:"Modern, interactive portfolio website showcasing experiences, projects, and skills with dynamic components and engaging UI elements.", icon:"🎨", tags:["Next.js","React","JavaScript","CSS"], stars:0, github:"https://github.com/aroudrasthakur/personal_website", demo:null, priority: 5 },
  { id:7, title:"Weather App", description:"A simple weather application that fetches and displays current weather data using the OpenWeatherMap API.", icon:"☀️", tags:["JavaScript","HTML","CSS","API"], stars:0, github:"https://github.com/aroudrasthakur/WeatherApp", demo:null, priority: 8 },
  { id:8, title:"Slang Detection LLM", description:"A language model fine-tuned to detect and interpret slang terms in social media text, enhancing sentiment analysis accuracy.", icon:"🗣️", tags:["Python","TensorFlow","NLP","Machine Learning"], stars:0, github:"https://github.com/aroudrasthakur/SlangDetectionLLM", demo:null, priority: 7 },
  { id:9, title:"Steering Wheel Angle Prediction", description:"Developed a deep learning model to predict steering wheel angles from road images using CNNs, enhancing autonomous driving capabilities.", icon:"🚗", tags:["Python","Keras","Computer Vision","Deep Learning"], stars:0, github:"", demo:null, priority: 5},
  { id:10, title:"Bod-Fix", description:"A fitness application that provides the user with a form correction tool to allow the users to perform exercises with the correct form using pose estimation techniques.", icon:"🏋️‍♂️", tags:["Python","OpenCV","Mediapipe","Flask"], stars:0, github:"", demo:null, priority: 8}
];

export function formatDate(dateStr){
  if(!dateStr) return 'Present';
  const [y,m]=dateStr.split('-');
  const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${months[parseInt(m)-1]} ${y}`;
}